### ISSUE TITLE
Please add gerber files to the repository

### ISSUE THREAD

**Issue by koppi** [madcowswe/ODriveHardware#1]
I do not have Altium, can you upload the gerber files to the repo?

**Comment by madcowswe** [comment]
I have been doing some testing in the past couple of weeks, and there are some bugs that I need to sort out before I'm comfortable recommending people to make their own copy.
As soon as I have fixed the bugs, I will upload the gerbers.

**Comment by jamwaffles** [comment]
I've just come across this repo and would also like the Gerbers as I can't get hold of Altium. Is the design in a state to be Gerber-ised now?

**Comment by jamwaffles** [comment]
Have these been added now? I had a quick look but couldn't find them. Might've missed something obvious though!
